default_language_version:
  python: python3.10

repos:
- repo: https://github.com/ambv/black
  rev: 22.1.0
  hooks:
  - id: black
- repo: https://github.com/PyCQA/pylint
  rev: v2.12.2
  hooks:
  - id: pylint
    entry: pipenv run pylint
- repo: https://github.com/PyCQA/bandit
  rev: 1.7.2
  hooks:
  - id: bandit
    entry: pipenv run bandit -r -x test
